var MSG = {
  title: "Kodo",
  blocks: "Blokoj",
  linkTooltip: "Konservi aliron al la blokoj.",
  runTooltip: "Ruli la programon difinita de la blokoj en la laborareo.",
  badCode: "Eraro de la programo:\n%1",
  timeout: "Se excedio el máximo de iteraciones ejecutadas permitidas.",
  trashTooltip: "Descartar todos los bloques.",
  catLogic: "Logiko",
  catLoops: "Cikloj",
  catMath: "Matematiko",
  catText: "Teksto",
  catLists: "Listoj",
  catColour: "Koloro",
  catVariables: "Variantoj",
  catFunctions: "Funkcioj",
  listVariable: "listo",
  textVariable: "teksto",
  httpRequestError: "Hubo un problema con la petición.",
  linkAlert: "Comparte tus bloques con este enlace:\n\n%1",
  hashError: "«%1» no corresponde con ningún programa guardado.",
  xmlError: "No se pudo cargar el archivo guardado.  ¿Quizá fue creado con otra versión de Blockly?",
  badXml: "Error de análisis XML:\n%1\n\nSelecciona OK para abandonar tus cambios o Cancelar para seguir editando el XML."
};
